### PR TITLE
added js project and cpp progs

### PR DESCRIPTION
**Pull request by diva-21**
Hello there,
Added a js project based on DOM
Also added important programs in c++ which are quite asked in interviews.
All the below added files are hard in leetcode and all are well commented , self explianatory
Added 2 Binary Tree questions , 2 Backtracking questions and a graph DSU based question

Kindly review it @khawajaazfar2000

### CODE REVIEW

**Comment by khawajaazfar** [comment]
You want me to do it? I am not maintainer of this repo.

**Comment by diva-21** [comment]
Yes you can do it

**Comment by diva-21** [comment]
Hello There, can you merge this PR as you have already reviewed it

**Comment by khawajaazfar2000** [comment]
As i said you earlier this is not my repo, so i can not merge you request, please contact owner of this repo only he can merge it

**Comment by khawajaazfar** [comment]
As i said you earlier this is not my repo, so i can not merge you request, please contact owner of this repo only he can merge it.
@diva-21

**Pull request closed without merging**
